---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1
  environments_path: ./test/environments
  data_bags_path: ./test/data_bags
  client_rb:
    environment: kitchen

platforms:
  - name: centos67
    driver_config:
      box: boxcutter/centos67
    attributes:
      system:
        primary_interface: eth1
  - name: centos71
    driver_config:
      box: boxcutter/centos71
    attributes:
      system:
        primary_interface: enp0s8
  - name: centos72
    driver_config:
      box: boxcutter/centos72
    attributes:
      system:
        primary_interface: enp0s8
  - name: ubuntu1404
    driver_config:
      box: boxcutter/ubuntu1404
    attributes:
      system:
        primary_interface: eth1
  - name: ubuntu1504
    driver_config:
      box: boxcutter/ubuntu1504
    attributes:
      system:
        primary_interface: eth1
  - name: debian82
    driver_config:
      box: boxcutter/debian82
    attributes:
      system:
        primary_interface: eth1

suites:
  - name: provisioner
    run_list: ["recipe[masala_chef::provisioner]"]
    driver:
      network:
      - ["private_network", {ip: "10.10.10.20"}]
      customize:
        memory: 1024
        cpus: 1
    attributes:
      system:
        short_hostname: 'chefprov1'
        static_hosts:
          10.10.10.20: chefprov1.kitchen.masalatest.com
          10.10.10.21: chefserver.kitchen.masalatest.com
      openldap:
        server: localhost
      ntp:
        servers: ["0.pool.ntp.org", "1.pool.ntp.org"]
  - name: server
    run_list: ["recipe[masala_chef::server]"]
    driver:
      network:
      - ["private_network", {ip: "10.10.10.21"}]
      customize:
        memory: 2048
        cpus: 2
    attributes:
      system:
        short_hostname: 'chefserver'
        static_hosts:
          10.10.10.20: chefprov1.kitchen.masalatest.com
          10.10.10.21: chefserver.kitchen.masalatest.com
      openldap:
        server: localhost
      ntp:
        servers: ["0.pool.ntp.org", "1.pool.ntp.org"]

